---
name: Object-Simple-Mixin-Meta
version: 0.0101
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: Mixin to get Object::Simple meta information
license: perl
resources:
  license: ~
build_requires:
  Object::Simple: 0.0203
  Test::More: 0
provides:
  Object::Simple::Mixin::Meta:
    file: lib/Object/Simple/Mixin/Meta.pm
    version: 0.0101
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
